pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nagateja96/escape-loading-animation"
        DOCKER_TAG   = "latest"

        SERVER_IP    = "172.31.29.127"
        SSH_USER     = "ubuntu"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKER_IMAGE:$DOCKER_TAG ./11.css-escape-loading-animation
                '''
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['server']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "
                        docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
                        docker stop app || true &&
                        docker rm app || true &&
                        docker run -d -p 80:80 --name app $DOCKER_IMAGE:$DOCKER_TAG
                    "
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "Deployment Successful"
        }
        failure {
            echo "Deployment Failed"
        }
    }
}
