pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "nagateja96/10.responsive-font-size"
        DOCKER_TAG     = "latest"
        EC2_HOST       = "ubuntu@172.31.83.17"
        CONTAINER_NAME = "10.responsive-font-size"
    }

    stages {

        stage('Checkout Code') {
    steps {
        git branch: 'master',
            url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
    }
}

        stage('Build Docker Image') {
            steps {
                sh '''
                cd 10.responsive-font-size
                docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
                '''
            }
        }

        stage('Push Docker Image') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                                          usernameVariable: 'USER',
                                          passwordVariable: 'PASS')]) {
            sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $DOCKER_IMAGE:$DOCKER_TAG
            '''
        }
    }
}
        stage('Deploy to EC2') {
            steps {
                sshagent(['app-server']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no $EC2_HOST "
                    docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
                    docker stop $CONTAINER_NAME || true &&
                    docker rm $CONTAINER_NAME || true &&
                    docker run -d -p 80:80 --name $CONTAINER_NAME $DOCKER_IMAGE:$DOCKER_TAG
                    "
                    '''
                }
            }
        }
    }
}
