pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nagateja96/10.responsive-font-size"
        DOCKER_TAG   = "latest"
        SERVER_IP    = "172.31.83.17"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG 10.responsive-font-size/'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                        echo $PASS | docker login -u $USER --password-stdin
                        docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['App-Server']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "
                        docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
                        docker stop app || true &&
                        docker rm app || true &&
                        docker run -d -p 3000:3000 --name app $DOCKER_IMAGE:$DOCKER_TAG
                        "
                    '''
                }
            }
        }

    }
}
