pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "nagateja96/10.responsive-font-size"
        DOCKER_TAG     = "latest"
        EC2_HOST       = "ubuntu@172.31.83.17"
        CONTAINER_NAME = "10.responsive-font-size"
    }

    stages {

        stage('Checkout Code') {
    steps {
        git branch: 'master',
            url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
    }
}

        stage('Build Docker Image') {
            steps {
                sh '''
                cd 10.responsive-font-size
                docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
                '''
            }
        }

        stage('Push Docker Image') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                                          usernameVariable: 'USER',
                                          passwordVariable: 'PASS')]) {
            sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $DOCKER_IMAGE:$DOCKER_TAG
            '''
        }
    }
}
       stage('Deploy') {
    steps {
        sshagent(['app-server']) {
            sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@172.31.83.17 "
                docker pull nagateja96/your-image:latest &&
                docker stop app || true &&
                docker rm app || true &&
                docker run -d -p 3000:3000 --name app nagateja96/your-image:latest
                "
            '''
        }
    }
}
