pipeline {
    agent any

   environment {
    DOCKER_IMAGE = "nagateja96/quiz-app"
    DOCKER_TAG = "latest"
    EC2_HOST = "ubuntu@52.87.192.5"
    CONTAINER_NAME = "quiz-app"
    PROJECT_DIR = "05.Quiz-App"   
}

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
            }
        }

      stage('Build Docker Image') {
    steps {
        dir("${PROJECT_DIR}") {
            sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
        }
    }
}

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['App-server']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} '
                            docker stop ${CONTAINER_NAME} || true
                            docker rm ${CONTAINER_NAME} || true
                            docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                            docker run -d -p 3000:80 --name quiz-app nagateja96/quiz-app:latest}
                        '
                    """
                }
            }
        }
    }
}
