pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "nagateja96/split-screen"
        DOCKER_TAG     = "latest"
        EC2_HOST       = "ubuntu@3.94.125.170"
        CONTAINER_NAME = "09.split-screen"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ./09.split-screen
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['nginx-server']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no ${EC2_HOST} "
                        docker pull ${DOCKER_IMAGE}:${DOCKER_TAG} &&
                        docker stop ${CONTAINER_NAME} || true &&
                        docker rm ${CONTAINER_NAME} || true &&
                        docker run -d -p 80:80 --name ${CONTAINER_NAME} ${DOCKER_IMAGE}:${DOCKER_TAG}
                    "
                    '''
                }
            }
        }
    }
}
