pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "nagateja96/lovely-movies"
        DOCKER_TAG   = "latest"
        EC2_HOST     = "ubuntu@3.94.125.170"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ramanagatejanetha-alt/front-end-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('02.lovely-movies') {
                    sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([string(credentialsId: 'docker-pass', variable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u nagateja96 --password-stdin
                        docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['App-server']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no $EC2_HOST "
                            docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
                            docker stop app || true &&
                            docker rm app || true &&
                            docker run -d -p 3000:3000 --name app $DOCKER_IMAGE:$DOCKER_TAG
                        "
                    '''
                }
            }
        }
    }
}
